version: "3.8"

services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    environment:
      - HOST=0.0.0.0

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/inventory_management_system

  mongodb:
    container_name: mongodb
    image: mongo
    expose:
      - "27017"
    volumes:
      - ./data:/data/db
    restart: always

  caddy:
    container_name: caddy
    image: caddy
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - client
      - server
    restart: always
